apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: mealie
    behavior: merge
    envs:
      - mealie.env

resources:
  - ../../base

patches:
  - patch: |-
      - op: add
        path: /spec/rules/0/host
        value: mealie.rcomanne.nl
    target:
      kind: Ingress
      name: mealie

  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/envFrom/-
        value: 
          secretRef: 
            name: mealie-database
            optional: false
    target:
      kind: Deployment
      name: mealie