apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
spec:
  template:
    spec:
      containers:
        - name: home-assistant
          volumeMounts:
            - mountPath: /config/default_configuration.yaml
              subPath: configuration.yaml
              name: home-assistant-config
      volumes:
        - name: home-assistant-data
          persistentVolumeClaim:
            claimName: pvc-home-assistant-config
            