---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-home-assistant-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: nfs-csi-default
  volumeMode: Filesystem