# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

homeassistant:
  name: Home
  unit_system: metric
  currency: EUR
  country: NL
  time_zone: "Europe/Amsterdam"
  internal_url: "http://homeassistant.local:8123"
