apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
spec:
  replicas: 1
  template:
    metadata:
      name: home-assistant
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
      containers:
        - name: home-assistant
          image: homeassistant/home-assistant:2024.1
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: "Europe/Amsterdam"
          ports:
            - containerPort: 8123
              name: web
          volumeMounts:
            - mountPath: /config
              name: home-assistant-data
          securityContext:
            privileged: false
      restartPolicy: Always
      volumes:
        - name: home-assistant-data
          emptyDir: {}

