apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: home-assistant

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

configMapGenerator:
  - name: home-assistant-config
    files:
      - configuration.yaml
    options:
      disableNameSuffixHash: true

labels:
  - pairs:
      app.kubernetes.io/name: home-assistant
    includeSelectors: true
  - pairs:
      app.kubernetes.io/version: "2024.1"
    includeSelectors: false