crds:
  enabled: true

global:
  pspEnabled: true

grafana:
  defaultDashboardsTimezone: browser

  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hosts:
      - grafana.rcomanne.nl
    path: /