apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mealie
spec:
  rules:
    - host:
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mealie
                port:
                  name: web