apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: akaunting/akaunting
    newTag: "3.1-fpm-alpine-nginx"

resources:
  - ../../base
  - storage.yaml

configMapGenerator:
  - name: akaunting-config
    behavior: merge
    envs:
      - run.env

labels:
  - pairs:
      app.kubernetes.io/version: "3.1"
    includeSelectors: false

patches:
  - patch: |-
      - op: add
        path: /spec/rules/0/host
        value: akaunting.rcomanne.nl
    target:
      kind: Ingress
      name: akaunting
  - patch: |-
      - op: replace
        path: /spec/template/spec/volumes/0
        value: 
          name: akaunting-data
          persistentVolumeClaim:
            claimName: pvc-akaunting-data
    target:
      kind: Deployment
      name: akaunting
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/envFrom/-
        value:
          secretRef:
            name: akaunting-database
            optional: false
      - op: add
        path: /spec/template/spec/containers/0/envFrom/-
        value:
          secretRef:
            name: akaunting-admin
            optional: false
    target:
      kind: Deployment
      name: akaunting